### PR TITLE
Update Gemfile.lock so lunr works under Ruby 1.9

### PR DESCRIPTION
**Pull request by PeterJCLaw**

### CODE REVIEW

**Comment by prophile** [comment]
Failing on the geo lookup for the Munich Hackerspace.

**Comment by jimmythompson** [comment]
Is 1.9 the agreed supported Ruby version? Is there a reason this isn't running on a later version?

**Comment by PeterJCLaw** [comment]
1.9 is the version I have to hand on my desktop machine (Ubuntu 14.04).
Ruby 2.2.2 is the version on saffron.
Is there any reason not to support both?

**Comment by jimmythompson** [comment]
I thought support (incl. security fixes) stopped for 1.9.x [back in Feburary](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/).

Right now, I doubt it matters. In addition, Jekyll is a static website generator, so I'd expect only static content to be uploaded to Saffron.

This PR seems to be an easy win, but I wouldn't suggest going out of the way to support 1.9.x.

**Comment by PeterJCLaw** [comment]
See #41 for the deployment handling, but my expectation is that we'll have puppet run (on saffron) the jekyll build and then copy the files into place.

As I understand it the single largest goal of moving to jekyll is that it'll be easier for everyone to edit the website with than srweb was. Not supporting major platforms would be a significant blocker to that goal.

@prophile any ideas why it failed on that lookup?

**Comment by prophile** [comment]
Unsure; I take it it works locally my?

**Comment by PeterJCLaw** [comment]
Yes

**Comment by prophile** [comment]
Oh lol, it's rate limiting on the API calls. Disregard.

**Comment by PeterJCLaw** [comment]
I see. Another reason that #43 is needed.

**Comment by PeterJCLaw** [comment]
srweb is long since dead.

**Pull request closed without merging**
